from nn_tools.losses.segmentation.entropy_based_losses import cross_entropy_with_logits_loss, focal_with_logits_loss
from nn_tools.losses.segmentation.overlap_based_losses import dice_with_logits_loss
from nn_tools.losses.segmentation.distance_based_losses import mse_with_logits_loss
